### ISSUE TITLE
Adding project tests hook/protocol

### ISSUE THREAD

**Issue by Guthur** [guicho271828/quicklisp-project-submission#2]
It would be interesting if this project could help collect, and encourage, project testing.

Possibly something that quicklisp could use in the future to provide build reports to uses of libraries e.g. all tests pass or there are some failures.

Thinking about something along the lines of what people use travis for in clojure projects like this https://github.com/clj-time/clj-time.

I would interested in your thoughts

**Comment by guicho271828** [comment]
I am currently very busy until 9/16, sorry for the halt in the development.

**Comment by guicho271828** [comment]
ok, I have some time before the experiments finish.

I listed the ideas I currently have in the github wiki. feel free to add your content.

**Comment by guicho271828** [comment]
I plan to make this issue page a task list. For a while, please add your idea to the wiki page. Meanwhile I will put them in this issues list when enough number of features are listed.
